### ISSUE TITLE
not able to mount postgres volume

### ISSUE THREAD

**Issue by bhargavkumar-65** [healenium/healenium-backend#29]
Hi,
Not able to mount  /var/lib/postgresql/data
tried with below in docker compose, Postgres goes into restart mode for every few seconds.

    volumes:
      - ./postgresData:/var/lib/postgresql/data

**Comment by GannaChernyshova** [comment]
Hi @bhargavkumar-65 ! Please provide your full docker-compose file

**Comment by bhargavkumar-65** [comment]
@GannaChernyshova
https://www.github.com/AutoInfra/HealeniumTestng/tree/master/DockerFiles%2FHealenium%2Fdocker-compose.yml
