### ISSUE TITLE
'No schema has been selected to create in' error 

### ISSUE THREAD

**Issue by r1vinay** [healenium/healenium-backend#38]
Hi,
Followed steps to start backend with docker-compose up, but I am facing 'liquidbase.exception.databaseException: ERROR: No schema has been selected to create in'.

Create Table databasechangeloglock.

Please let me know if healenium/hlm-backend:latest has this issue.

**Comment by ElenaStepuro** [comment]
Hi @r1vinay !
Looks like you didn't get the init.sql file.
Please, check that you configured docker-compose and init.sql as shown in this folder example:
https://github.com/healenium/healenium-example-maven/tree/master/infra
