### ISSUE TITLE
Caused by: org.postgresql.util.PSQLException: Connection to db:5432 refused

### ISSUE THREAD

**Issue by naveenkmr2310** [healenium/healenium-backend#48]
Hi team,

When you try to integrate healenium-backend using docker compose command, the images are being created but while starting the container it is exiting with exit code 1. The console error messages are posted below for your reference. Any leads on this will be helpful.

PS: 5432 port and 7878 ports are not occupied in local system.
![282603E6-8D72-422B-899E-0F34F5808B1D](https://user-images.githubusercontent.com/66383805/145069290-ff3ee2e4-0fba-456e-ae5c-6bd2837bf03b.jpeg)
![11B471C6-136A-4272-8255-ECF2207BCCA8](https://user-images.githubusercontent.com/66383805/145069304-ea557362-cbe8-4f2e-8afa-a7b40a6c85b6.jpeg)

**Comment by ElenaStepuro** [comment]
Hello @naveenkmr2310 !
Please, provide your docker-compose file
