### ISSUE TITLE
Healenium backend configuration in Openshift pod

### ISSUE THREAD

**Issue by divya2021** [healenium/healenium-backend#53]
I tried to invoke the Healenium backend in openshift Pod to handle connection issues in GIt lab CI/CD.

We created two pods for healenium backend and Postgres. The complete master branch code has been deployed in openshift pod. But we were facing issues in creating the pod for Postgres. The schema files are not getting deployed in postgres, whether execution of backend will also trigger the postgres schema deployment as well?

Without using docker-compose, is it possible to deploy postgres with schema files?

Thanks!!

**Comment by Aliaksei-Ashukha** [comment]
Hi @divya2021 , We have helm chart for deploy healenium on Kubernetes: https://github.com/healenium/kubernetes
