### ISSUE TITLE
[Need support]: to fetch healed xpath at runtime

### ISSUE THREAD

**Issue by Akhil423** [healenium/healenium-backend#69]
### Describe the problem

I have explored most of the classes in java library but could not find a functionality to fetch healed xpath using hlm backend

would like to fetch healed xpath produced by healenium and update my locators list

### Healenium Web version

3.3.1

### Healenium Backend version

3.2.2

### Selenium version

4.1.4

### Platform

java

### Logs appeared during using Healenium

```shell
NA
```

### Additional context

I have explored most of the classes in java library but could not find a functionality to fetch healed xpath using hlm backend

would like to fetch healed xpath produced by healenium and update my locators list

**Comment by Alex-Reif** [comment]
Hi @Akhil423 , Currently, Healenium build css selector as for healed locator. In some cases Healenium can return xpath locator, but is depends on many conditions. Unfortunately, we cannot promise you will receive xpath by default.
