### ISSUE TITLE
[Need support]: New report endpoints

### ISSUE THREAD

**Issue by erikzimmermann** [healenium/healenium-backend#70]
### Describe the problem

I need to access the report contents in my code to log healed elements but unfortunately there is no endpoint for that yet.

Adding following endpoints to the ReportController would already be sufficient.
```java
    @GetMapping("/data/{uid}")
    public RecordDto getRecord(@PathVariable String uid) {
        return reportService.generate(uid);
    }

    @GetMapping("/data")
    public RecordDto getRecords() {
        return reportService.generate();
    }
```

### Healenium Web version

N/A

### Healenium Backend version

N/A

### Platform

Java

### Logs appeared during using Healenium

```shell
N/A
```

**Comment by Alex-Reif** [comment]
Hi @erikzimmermann , merged in the hlm-backend 3.4.0
