### ISSUE TITLE
[BUG]: unable transform windows path in Reports web page

### ISSUE THREAD

**Issue by PraneethMusunuru** [healenium/healenium-backend#74]
### Describe the bug

Unable to view screenshots in reports page

### How to reproduce the issue

```shell
Just open report web page in windows machine u will not able to view the screen shots.
```

### Logs appeared during using Healenium

```shell
Error transform source path
```

### Healenium Web version

None

### Healenium Backend version

3.3.4

### Selenium version

4

### Platform

Java

### Additional context

Please use File.seperator instead of  "/"  in 
ReportServiceImpl.java (transformPath method)
then the issue would be resolved.

**Comment by Alex-Reif** [comment]
Hi @PraneethMusunuru , Thanks for you, we fixed the issue in the hlm-backend 3.4.0. Update service please.
