### ISSUE TITLE
[BUG]: Report is not generating if we are using selenium version 4.14.0 with latest Healenium backend.

### ISSUE THREAD

**Issue by dipaksingh0015** [healenium/healenium-backend#80]
### Describe the bug

Report is not generating if we are using selenium version 4.14.0 with latest Healenium backend.

### How to reproduce the issue

```shell
Use latest healenium backend and start the server
Use selenium version 4.14.0 and execute the script.
```

### Logs appeared during using Healenium

```shell
NA
```

### Expected behavior

report should generate after execution.

### Actual behavior

Report is not generating after execution.

### Healenium Web version

3.4.6

### Healenium Backend version

3.4.1

### Selenium version

4.14.0

### Platform

Java

**Comment by Alex-Reif** [comment]
Fixed in the healenium-web:3.4.8
