### ISSUE TITLE
[Need support]: What is the minimum java version required to run latest healenium backend server.

### ISSUE THREAD

**Issue by dipaksingh0015** [healenium/healenium-backend#81]
### Describe the problem

What is the minimum java version required to run latest healenium backend server.

### Healenium Web version

3.4.6

### Healenium Backend version

3.4.1

### Platform

Java

### Logs appeared during using Healenium

```shell
NA
```

**Comment by Alex-Reif** [comment]
Hi @dipaksingh0015 , Java 17
